# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20170426_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
